
CREATE TABLE FRAIS_DOSSIER (ID bigint not null, MONTANT NUMERIC(10, 2) not null, DATE_DEBUT_VALIDITE date not null, DATE_FIN_VALIDITE date, primary key (id));

ALTER TABLE Sejour ADD COLUMN FRAIS_DOSSIER NUMERIC(10, 2);
UPDATE Sejour SET FRAIS_DOSSIER = 0 WHERE FRAIS_SEJOUR_JOURNALIER IS NULL;