
CREATE TABLE FRAIS_VOYAGE (ID bigint not null, MONTANT NUMERIC(10, 2) not null, DATE_DEBUT_VALIDITE date not null, DATE_FIN_VALIDITE date, primary key (id));

ALTER TABLE Sejour ADD COLUMN FRAIS_VOYAGE NUMERIC(10, 2);
UPDATE Sejour SET FRAIS_VOYAGE = 0 WHERE FRAIS_VOYAGE IS NULL;