
CREATE TABLE FRAIS_PENSION_FAMILLE_JOURNALIER (ID bigint not null, MONTANT NUMERIC(10, 2) not null, DATE_DEBUT_VALIDITE date not null, DATE_FIN_VALIDITE date, primary key (id));

ALTER TABLE Sejour ADD COLUMN FRAIS_PENSION_FAMILLE_JOURNALIER NUMERIC(10, 2);
UPDATE Sejour SET FRAIS_PENSION_FAMILLE_JOURNALIER = 0 WHERE FRAIS_PENSION_FAMILLE_JOURNALIER IS NULL;